{{- if .Values.gpuSupport.enabled }}

{{- if or (eq "hybrid" .Values.gpuSupport.nodes) (eq "all" .Values.gpuSupport.nodes) }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "scaphandre.name" . }}-gpu
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{ include "scaphandre.daemonset.spec" (dict "Values" .Values "context" . "gpuPresent" true) }}
{{- end }}

{{- if eq "hybrid" .Values.gpuSupport.nodes }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "scaphandre.name" . }}-nongpu
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{ include "scaphandre.daemonset.spec" (dict "Values" .Values "context" . "gpuPresent" false) }}
{{- end }}

{{- else }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "scaphandre.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
{{ include "scaphandre.daemonset.spec" (dict "Values" .Values "context" . "gpuPresent" false) }}

{{- end }}